net_parameters:
    eps: 1e-20
    hidden_dim: 200
    negative_slope: 0.1
    activation_str: 'leaky_relu'
    generator_output_activation_str: None

train_parameters:
    N_train: 100_000
    N_test: 100_000
    batch_size: 1_000
    c_lr: 1.05
    cut_lr_every: 500
    epochs: 200
    beta1: 0.5
    beta2: 0.999
    lr_G: 0.0001
    lr_D: 0.0005
    n_D: 2

meta_parameters:
    preset_str: 'CIR_Feller_violated_high_gamma'
    proc_type_str: 'scale_S_ref'
    supervised: False
    seed: 42
    save_figs: False
    save_iter_plot: False
    report: False
    plot_interval: int
    seed: int
    output_name: 'output'
    enable_cuda: True
