net_parameters:
    eps: 0.00000000000000000000000000000000000000000000000000000000001
    hidden_dim: 200
    negative_slope: 0.1
    activation_str: 'leaky_relu'
    generator_output_activation_str: None

train_parameters:
    n_train: 100_000
    batch_size: 1_000
    c_lr: 1.05
    cut_lr_every: 500
    epochs: 200
    beta1: 0.5
    beta2: 0.999
    lr_G: 0.0001
    lr_D: 0.0005
    n_D: 2

test_parameters:
    n_test: 100_000
    test_condition:
        S0: 0.1
        dt: 1

meta_parameters:
    preset_str: 'gbm'
    proc_type_str: 'scale_S_ref'
    S_ref: 0.1
    eps: 0.00000000000000000000000000000000000000000000000000000000001
    supervised: True
    seed: 42
    save_figs: False
    save_iter_plot: False
    save_log_dict: True
    plot_interval: 500
    output_name: 'output/gbm'
    enable_cuda: True
    conditional_gan: True

plot_parameters:
    noise_samples: 10_000
    save_fig: False
    save_dir: './output/plots/'
    n_points: 1_000