c_lr: 1.05
cut_lr_every: 500
epochs: 200
eps: 1e-20
batch_size: 1000
hidden_dim: 200
preset: 'CIR_Feller_violated_high_gamma'
N_train: 100_000
N_test: 100_000
activation: 'leaky_relu'
negative_slope: 0.1
proc_type: 'scale_S_ref'
output_activation: None
beta_1: 0.5
beta_2: 0.999
lr_G: 0.0001
lr_D: 0.0005
n_D: 2
supervised: False
seed: 42
save_figs: False
save_iter_plot: True
report: False
results_path: './output'
plot_interval: 500
